function gca=boxoff(gca)
box off
ax2 = axes('Position',get(gca,'Position'),...
    'Color','none',...
    'XAxisLocation','top',...
    'YAxisLocation','right',...
    'XColor','k','YColor','k','LineWidth',3);
set(ax2,'YTick', []);
set(ax2,'XTick', []);
end